name: Python Workflow

on:
  push:

jobs:
  run_python_program:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Run Python program
      run: python batch10.py  # Replace my_program.py with the name of your Python program

      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
 
      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build, 
        echo test, and deploy your project.
